# Generated by Django 4.2.1 on 2023-05-24 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0003_contactmessage_delete_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactmessage',
            name='name',
            field=models.CharField(default='MARK SHIJA', max_length=50),
        ),
    ]
