# Generated by Django 4.2.1 on 2023-05-24 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0005_auto_20230524_1930'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactmessage',
            name='name',
            field=models.CharField(default='', max_length=50),
        ),
    ]
